# Generated by Django 4.2.20 on 2025-04-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '书籍分类',
                'verbose_name_plural': '书籍分类',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='位置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='位置描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '存放位置',
                'verbose_name_plural': '存放位置',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='书名')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN号')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('image_url', models.CharField(blank=True, max_length=512, verbose_name='封面图片URL')),
                ('status', models.CharField(choices=[('available', '可借'), ('borrowed', '已借出'), ('lost', '丢失'), ('damaged', '损坏'), ('reserved', '已预约')], default='available', max_length=20, verbose_name='状态')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='所属分类')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.location', verbose_name='存放位置')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'books',
            },
        ),
    ]
